# Copyright (c) 2024 Ho Kim (ho.kim@ulagbulag.io). All rights reserved.
# Use of this source code is governed by a GPL-3-style license that can be
# found in the LICENSE file.

# Load environment variables
set dotenv-load

deploy:
  kubectl apply -f deployment-toolkit.yaml -f pvc.yaml

start *ARGS:
  kubectl delete -f deployment-disk-io.yaml || true
  kubectl apply -f deployment-disk-io.yaml
  kubectl wait --for=condition=ready pods -l 'app.kubernetes.io/component=perf-test-disk-io'

exec *ARGS:
  @kubectl exec -it -c shell 'deployment/perf-test-toolkit' -- {{ ARGS }}

_stat_avg rw:
  @echo "1024 * $( \
    just exec cat '/data/perf-test-disk-io_{{ rw }}.log' \
      | grep -P '^ +bw' \
      | grep -Po 'avg=\K[0-9\.]+' \
      | bc \
  )" | bc

stat:
  @echo -n 'read (bps) '
  @just _stat_avg 'read'
  @echo -n 'write (bps) '
  @just _stat_avg 'write'
  @echo -n 'randread (bps) '
  @just _stat_avg 'randread'
  @echo -n 'randwrite (bps) '
  @just _stat_avg 'randwrite'
